# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ⚡ AstroROM Floating Features ⚡
# Device: Galaxy S20 FE (Qualcomm, r8q)
# Firmware Base: OneUI 8.0 / Android 16
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 🚫 Disabled / Unsupported Features
FF "AUDIO_CONFIG_MIC_POSITION" ""
FF "AUDIO_SUPPORT_MICMODE_QUICK_PANEL" ""
FF "AUDIO_SUPPORT_SITUATION_EXTENSION" ""
FF "AUDIO_SUPPORT_VOIP_VIA_SMART_MONITOR" ""
FF "BATTERY_SUPPORT_BSOH_GALAXYDIAGNOSTICS" ""
FF "BATTERY_SUPPORT_PASS_THROUGH" ""
FF "BIXBY_SUPPORT_BIXBYKWD" ""
FF "CAMERA_CONFIG_AIFRC_SPEC" ""
FF "CAMERA_CONFIG_GALAXYRAW_PLATFORM_VERSION" ""
FF "CAMERA_CONFIG_GPPM_SOLUTIONS" ""
FF "CAMERA_CONFIG_SDK_FEATURE_INFO" ""
FF "CAMERA_SUPPORT_30FPS_ALL_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_4K_PORTRAITVIDEO" ""
FF "CAMERA_SUPPORT_AFSKIP" ""
FF "CAMERA_SUPPORT_AIFRC" ""
FF "CAMERA_SUPPORT_AI_HIGH_RESOLUTION" ""
FF "CAMERA_SUPPORT_GALLERY_LR" ""
FF "CAMERA_SUPPORT_HIGH_RESOLUTION_MEMORY_CHECK" ""
FF "CAMERA_SUPPORT_HYPERLAPSE_VDISONOFF" ""
FF "CAMERA_SUPPORT_LOGICAL_CAMERA" ""
FF "CAMERA_SUPPORT_PRO_RGB_CONVERSION" ""
FF "CAMERA_SUPPORT_VDIS_PORTRAITVIDEO" ""
FF "COMMON_CONFIG_EMBEDDED_SIM_SLOTSWITCH" ""
FF "COMMON_SUPPORT_COLOR_LENS" ""
FF "COMMON_SUPPORT_HDR_EFFECT" ""
FF "GRAPHICS_SUPPORT_AUTO_CONTROL_DEFAULT" ""
#FF "LCD_SUPPORT_EXTRA_BRIGHTNESS" ""
FF "LCD_SUPPORT_MDNIE_HW" ""
FF "LCD_SUPPORT_SELFMASK" ""
FF "LOCKSCREEN_CONFIG_SUBDISPLAY_POLICY" ""
FF "MMFW_SUPPORT_HW_HDR" ""
FF "MMFW_SUPPORT_LONGEXPOSURE_EFFECT" ""
#FF "MSCH_SUPPORT_NLSEARCH" ""
FF "SYSTEM_SUPPORT_LOW_HEAT_MODE" ""
FF "VIDEO_CONFIG_VIDEO_CLIPPING_MODE" ""
FF "WIFI_SUPPORT_ADPS" ""

# 🎧 Audio
FF "AUDIO_CONFIG_INTERPRETER" "0"
FF "AUDIO_CONFIG_MULTI_MIC" "2"
FF "AUDIO_CONFIG_SOUNDALIVE_VERSION" "eq_custom,uhq_onoff,karaoke,adapt,spk_stereo,dvfs_35_percent"
FF "AUDIO_CONFIG_VOLUMEMONITOR_GAIN" "3"

# 🔑 Fingerprint Sensor
FF "BIOAUTH_CONFIG_FINGERPRINT_FEATURES" "optical_display_phone"

# 🎙️ Bixby
FF "BIXBY_CONFIG_CUSTOM_FIRMWARE" "0"
FF "BIXBY_SUPPORT_CUSTOM_WAKEUP" "1"

# 📷 Camera
FF "CAMERA_CONFIG_AI_HIGH_RESOLUTION_MAX_CAPTURE" "1"
FF "CAMERA_CONFIG_AVATAR_MAX_FACE_NUM" "1"
FF "CAMERA_CONFIG_CAMID_TELE_STANDARD_CROP" "-1"
FF "CAMERA_CONFIG_CAMID_UW" "2"
FF "CAMERA_CONFIG_CAMID_WIDE" "0"
FF "CAMERA_CONFIG_NIGHT_FRONT_DISPLAY_FLASH_TRANSPARENT" "85"
FF "CAMERA_CONFIG_PERSONALIZATION" "CoolOriWarm"
FF "CAMERA_CONFIG_QRCODE_INTERVAL" "500"
FF "CAMERA_CONFIG_UW_DISTORTION_CORRECTION" "0,109,2,19010403,4000,3000,0,0,0,0"
FF "CAMERA_CONFIG_VENDOR_LIB_INFO" "image_codec.samsung.v1,beauty.samsung.v4,face_landmark.arcsoft.v2_1,facial_attribute.samsung.v1,super_resolution.arcsoft.v2_1,super_night.mpi.v2,event_detection.samsung.v2,food.samsung.v1,selfie_correction.samsung.v1,mfhdr.arcsoft.v3,llhdr.arcsoft.v3,swuwdc.arcsoft.v1,human_tracking.arcsoft.v2_1,single_bokeh.samsung.v2,human_segmentation.samsung.v2,smart_scan.samsung.v2,dual_bokeh.samsung.v1_1,image_enhance.arcsoft.v1,high_res.arcsoft.v1,localtm.samsung.v1_1,scene_detection.samsung.v1"
FF "CAMERA_CONFIG_VERSION_FILTER_PROVIDER" "5"
FF "CAMERA_CONFIG_HIGH_RESOLUTION_MAX_CAPTURE" "0"
FF "CAMERA_CONFIG_WIDE_DISTORTION_CORRECTION" "0,0,0,0,0,0,0,0,0,0"
FF "CAMERA_DOCUMENTSCAN_SOLUTIONS" "CV_DEWARPING"
FF "CAMERA_GRAW_CONFIG_MFP_PIPELINE_MODE" "V1"
FF "CAMERA_SUPPORT_NIGHT_FRONT_DISPLAY_FLASH" "false"
FF "COMMON_CONFIG_SWLENS_DISTORTION_CORRECTION" "r8,S5K3L6"
FF "SAIV_CONFIG_MIDAS" "UPSCALE,LOWLIGHT,HDR,DEBLUR,MOIRE,DENOISE_DEBLUR,UPSCALE_DEBLUR,PHOTOPOLISH,SHADOW,REFLECTION,UWDC"
FF "VISION_CONFIG_RELIGHTING_SOLUTION" "arcsoft_effectonly.v1"

# 🌈 Display
FF "COMMON_CONFIG_MDNIE_MODE" "45073"
FF "COMMON_CONFIG_DYN_RESOLUTION_CONTROL" "WQHD,FHD,HD"
FF "LCD_CONFIG_CONTROL_AUTO_BRIGHTNESS" "4"
FF "LCD_CONFIG_HFR_MODE" "2"
FF "LCD_CONFIG_HFR_SUPPORTED_REFRESH_RATE" "120,60"
FF "LCD_CONFIG_NIGHT_DIM" "0"
FF "LCD_SUPPORT_BLUE_FILTER_ADAPTIVE_MODE" "2"

# 🛠 Frameworks
FF "FRAMEWORK_SUPPORT_TSP_STATE_MANAGER" "deadzone_v2,change_ratio"
FF "SYSTEM_CONFIG_SIOP_POLICY_FILENAME" "siop_r8q_sm8250"

# 🖼️ Samsung Gallery
FF "GALLERY_CONFIG_AI_EXPANSION" "AI_Timelapse"
FF "GALLERY_CONFIG_FACE_CLUSTER_VERSION" "SRCB_V3"
FF "GALLERY_CONFIG_IMAGE_TAGGER_VERSION" "V516"
FF "GALLERY_CONFIG_PET_CLUSTER_VERSION" "None"
FF "GALLERY_CONFIG_ZOOM_TYPE" "ZOOM_5K"

# 🔒 Lockscreen
FF "LOCKSCREEN_CONFIG_PUNCHHOLE_VI" "face,pos:0.5:0.025,size:0.1204:0.0542,type:circle"
FF "LOCKSCREEN_CONFIG_WALLPAPER_STYLE" "MOTION,VIDEO"

# 📱 Device Specific
FF "COMMON_CDMALESS" "VZW,USC"
FF "SECURITY_SUPPORT_STRONGBOX" "TRUE"
FF "SECURITY_SUPPORT_STRONGBOX_API" "TRUE"
FF "SETTINGS_CONFIG_BRAND_NAME" "Galaxy S20 FE"
FF "SETTINGS_CONFIG_ELECTRIC_RATED_VALUE" "DC 9 V; 1.67 A / DC 9 V; 2.77 A"
FF "SETTINGS_CONFIG_FCC_ID" "A3LSMG780G,9_A3LSMG780G1"
FF "SYSTEM_SUPPORT_ENHANCED_CPU_RESPONSIVENESS" "TRUE"
